version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 6.15.0
    - 8.1.0
    - 8.2.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 2.34.0
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 2.34.0
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: rollup
    versions:
    - 2.38.0
    - 2.38.3
    - 2.38.5
    - 2.39.0
    - 2.40.0
    - 2.41.2
    - 2.42.2
    - 2.43.1
    - 2.44.0
    - 2.45.1
  - dependency-name: jest-localstorage-mock
    versions:
    - 2.4.6
    - 2.4.7
    - 2.4.8
    - 2.4.9
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.5
    - 24.1.9
    - 24.3.1
    - 24.3.2
    - 24.3.4
    - 24.3.5
  - dependency-name: ts-jest
    versions:
    - 26.4.4
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: eslint-plugin-unicorn
    versions:
    - 28.0.2
    - 29.0.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
  - dependency-name: svelte
    versions:
    - 3.31.2
    - 3.32.1
    - 3.32.3
    - 3.34.0
    - 3.35.0
  - dependency-name: typescript
    versions:
    - 3.9.7
    - 3.9.9
    - 4.2.2
    - 4.2.3
  - dependency-name: "@rollup/plugin-replace"
    versions:
    - 2.3.4
    - 2.4.0
    - 2.4.1
  - dependency-name: eslint-plugin-svelte3
    versions:
    - 3.0.0
    - 3.1.1
    - 3.1.2
  - dependency-name: "@fullhuman/postcss-purgecss"
    versions:
    - 3.1.3
    - 4.0.2
  - dependency-name: prettier-plugin-svelte
    versions:
    - 2.1.1
    - 2.1.2
    - 2.1.4
    - 2.1.6
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.3.1
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.0
    - 11.1.1
    - 11.2.0
  - dependency-name: tslib
    versions:
    - 2.1.0
  - dependency-name: rollup-plugin-postcss
    versions:
    - 3.1.8
  - dependency-name: bulma
    versions:
    - 0.9.1
