extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:jest/recommended
  - plugin:promise/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:unicorn/recommended
  - prettier
  - prettier/@typescript-eslint
overrides:
  - files: "*.config.js"
    env: {node: true}
  - files: "src/**/*"
    env: {browser: true}
  - files: "**/*.svelte"
    processor: svelte3/svelte3
plugins:
  - svelte3
rules:
  "@typescript-eslint/camelcase": off
  unicorn/prevent-abbreviations: off
settings:
  import/resolver:
    node:
      extensions: [".js", ".ts"]
