extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:jest/recommended
  - plugin:promise/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:unicorn/recommended
  - prettier
  - prettier/@typescript-eslint
  - prettier/unicorn
overrides:
  - files: "*.config.js"
    env: {node: true}
    rules:
      import/no-default-export: off
  - files: "src/**/*"
    env: {browser: true}
  - files: "**/*.svelte"
    processor: svelte3/svelte3
    rules:
      unicorn/filename-case: off
plugins:
  - svelte3
rules:
  "@typescript-eslint/camelcase": off
  import/no-default-export: error
  import/no-unresolved: [error, {ignore: ["@routes@"]}]
  unicorn/catch-error-name: [error, {name: "err"}]
  unicorn/prevent-abbreviations: off
  unicorn/no-null: warn
settings:
  import/resolver:
    node:
      extensions: [".js", ".ts"]
