language: node_js
node_js: node
cache: npm

script:
  - npx eslint '**/*.{js,svelte}'
  - npm test
  - npm run build

after_success:
  - npm run coverage

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: $FLOYD_CI_DOMAIN
  on:
    branch: master
