language: node_js
node_js: node
cache: npm

script:
  - npx prettier --check '**/*'
  - npx eslint '**/*.{js,svelte}'
  - npx nyc ava --verbose
  - npm run build

after_success:
  - npx nyc report --reporter=text-lcov | npx coveralls

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: $FLOYD_CI_DOMAIN
  on:
    branch: master
