language: node_js
node_js: node
cache: npm

script:
  - npx prettier --check '**/*'
  - npx eslint '**/*.{js,ts,svelte}'
  - npx jest --coverage
  - npx rollup -c

after_success:
  - cat coverage/lcov.info | npx coveralls

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: $FLOYD_CI_DOMAIN
  on:
    branch: master
